spring.application.name=back-end
spring.main.allow-bean-definition-overriding=true
spring.main.banner-mode=off
# - Validation Regex for API User inputs.
email-validation-regex=^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
password-simple-validation-regex=^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])..{6,20}$

# -------------------------
# Data Persistence
# -------------------------
##  Database connectivity and Management

### MySQL Database connection
spring.datasource.url=${MYSQL_DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}

### MongoDB
spring.data.mongodb.uri=${MONGO_DB_URL}

### JPA
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#### Hibernate
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ------------------------
# Web
# ------------------------
## General settings
spring.web.resources.static-locations=classpath:/static/
api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M
management.endpoint.health.show-details=always
management.health.db.enabled=true

## Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

