spring.application.name=back-end

# Model Validations
email-validation-regex=^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
password-simple-validation-regex=^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{4,8}$
password-complex-validation-regex=^(?:(?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])\
  (?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))\
  (?!.*(.)\1{2,})[A-Za-z0-9!~<>,;:_=?*+#."&§%°()\|\[\]\-\$\^\@\/]{12,128}$

# -------------------------
# Data Persistence
# -------------------------
##  Database connectivity and Management
### MySQL Database connection
spring.datasource.url=${MYSQL_DB_URL}
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}
### MongoDB
spring.data.mongodb.uri=${MONGO_DB_URL}
### JPA
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#### Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


management.endpoint.health.show-details=always
management.health.db.enabled=true

api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M

spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8