package com.project.back_end.services;

import com.project.back_end.exceptions.DatabaseAccessException;
import com.project.back_end.exceptions.ParseJwtTokenException;
import com.project.back_end.repo.AdminRepository;
import com.project.back_end.repo.DoctorRepository;
import com.project.back_end.repo.PatientRepository;

import com.project.back_end.utils.outputhelpers.MessageFormatter.MessageHead;
import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.function.Function;

@Component
public class TokenService {
    private static final Logger logger = LoggerFactory.getLogger(TokenService.class);
    private final AdminRepository adminRepo;
    private final DoctorRepository doctorRepo;
    private final PatientRepository patientRepo;
    private final int JWT_TOKEN_EXPIRATION_DAYS = 7;
    private final String JWT_SECRET;
    
    public TokenService(AdminRepository adminRepo, DoctorRepository doctorRepo, PatientRepository patientRepo,
                        @Value("${jwt.secret}") String jwt_secret) {
        this.adminRepo = adminRepo;
        this.doctorRepo = doctorRepo;
        this.patientRepo = patientRepo;
        this.JWT_SECRET = jwt_secret;
    }
    
    /**
     * This method retrieves the HMAC SHA key used to sign JWT tokens.
     * @return HMAC SHA SecretKey
     */
    public SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(JWT_SECRET.getBytes(StandardCharsets.UTF_8));
    }
    
    /**
     * This method generates a JWT token for a user based on their email.<p>
     * * The `subject` of the token is set to the user's email, which is used as an identifier.<br>
     * * The `issuedAt` is set to the current date and time.<br>
     * * The `expiration` is set to 7 days from the issue date, ensuring the token expires after one week.<br>
     * * The token is signed using the signing key generated by `getSigningKey()`, making it secure and tamper-proof.</p>
     * @return JWT token as a String
     */
    public String generateToken(String subject) {
        Date issuedAt = Date.from(Instant.now());
        Date expireAt = Date.from(Instant.now().plus(JWT_TOKEN_EXPIRATION_DAYS, ChronoUnit.DAYS));
        
        String jws = Jwts.builder()
            .subject(subject)
            .issuedAt(issuedAt)
            .expiration(expireAt)
            .signWith(getSigningKey())
            .compact();
        
        logger.info("{}generateToken:: {}", MessageHead.SUCCESS.compose(), "JWT Token generated for subject: " + subject);
        return jws;
    }

    /**
     * This method extracts the user's email (subject) from the provided JWT token.<p>
     * * The token is first verified using the signing key to ensure it hasn’t been tampered with.<br>
     * * After verification, the token is parsed, and the subject (which represents the email) is extracted.</p>
     * @param token JWT token to be parsed
     * @return email extracted from subject
     */
    public String extractEmail(String token) {
        String email = extractClaim(token, Claims::getSubject);
        if (email == null || email.isBlank()) {
            logger.warn("{}extractEmail:: {}", MessageHead.FAIL.compose(), "Fail JWT token extraction for subject email with token: " + token);
            return "";
        } else {
            logger.info("{}extractEmail:: {}", MessageHead.SUCCESS.compose(), "Success JWT token extraction for subject email: " + email);
            return email;
        }
    }
    
    /**
     * This method extracts the admin's username (subject) from the provided JWT token.<p>
     * * The token is first verified using the signing key to ensure it hasn’t been tampered with.<br>
     * * After verification, the token is parsed, and the subject (which represents the username) is extracted.</p>
     * @param token JWT token to be parsed.
     * @return username extracted from subject.
     */
    public String extractUsername(String token) {
        return extractClaim(token, Claims::getSubject);
    }
    
    /**
     * This method extracts the expiration date from the provided JWT token, and checks if it has already expired.<p>
     * @param token JWT token to be parsed.
     * @return true if it has expired, false on contrary.
     */
    public boolean isTokenExpired(String token) {
        return extractClaim(token, Claims::getExpiration).before(new Date());
    }
    
    /**
     * This method extracts one claims from a map of Claims first extracted from the JWT token.<p>
     * @param token JWT to extract the Claim
     * @param claimsResolver function to extract a specific Claim.
     * @return the extracted value from the specified Claim.
     * @param <T> t
     */
    private <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }
    
    /**
     * This method extracts all claims from the provided JWT token.<p>
     * * The token is first verified using the signing key to ensure it hasn’t been tampered with.<br>
     * * After verification, the token is parsed, and all claims are passed to further individual extraction.</p>
     */
    public Claims extractAllClaims(String token) {
        try {
            return Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
        
        } catch (Exception e) {
            throw new ParseJwtTokenException("Error while parsing JWT Token to extract all Claims");
        }
    }

    /**
     * This method validates whether a provided JWT token is valid for a specific user role (admin, doctor, or patient).<p>
     * * It first extracts the email from the token using the `extractEmail()` method.<br>
     * * Depending on the role (`admin`, `doctor`, or `patient`), it checks the corresponding repository
     *   (AdminRepository, DoctorRepository, or PatientRepository) to see if a user with the extracted email exists.<br>
     * * The method gracefully handles any errors by returning false if the token is invalid or an exception occurs.</p>
     * @param token JWT validated by subject email / username checked against repository
     * @param user role to determine repository target
     * @return boolean true if a match is found for the specified user role, indicating the token is valid. Otherwise,
     *         it returns false, indicating the token is invalid.
     */
    public boolean isValidToken(String token, String user) {
        try {
            return switch (user) {
                case "admin" -> adminRepo.findByUsername(extractUsername(token)).isPresent() && !isTokenExpired(token);
                case "doctor" -> doctorRepo.findByEmail(extractEmail(token)).isPresent() && !isTokenExpired(token);
                case "patient" -> patientRepo.findByEmail(extractEmail(token)).isPresent() && !isTokenExpired(token);
                default -> false;
            };
        } catch (Exception e) {
            throw new DatabaseAccessException("Error in isValidToken while accessing to repositories.");
        }
    }
}
